### PR TITLE
[NOT READY: feedback only] WIP Profiler

### PR DESCRIPTION
**Pull request by dualcoding**
@goldpaw

Couldn't figure out how to get debuglocals (==standard Lua debug.locals?) to work, so currently have to manually add all traced functions to a table for it to work. Bummer.

Have a look if you're interested, maybe you'll have better luck.

EDIT: oops, forgot to mention, CVar "scriptProfile" needs to be set to "1"!

### CODE REVIEW

**Comment by Kkthnx** [comment]
Oh, this looks nice @dualcoding

**Comment by dualcoding** [comment]
Alright, so I can at least get it to automatically profile the "public" module API and set it to include called subroutines. Useful enough? Maybe a hybrid mode would work OK if a proper solution (getlocals) can't be done.

**Comment by dualcoding** [comment]
For the record debuglocals() is *not* a viable solution because:
1) it returns a string
2) that string has a maxlength and will abruptly end if exceded (the engine basically does this by itself)
3) there may or may not be a way to convert the found function names to addresses

If I'd taken a closer look at 2&3 *before* writing and debugging a recursive descent parser to solve 1, I'd have a couple of extra hours left of my life. Oh well.

**Comment by dualcoding** [comment]
I have a far more useful and flexible design in mind. Closing for now!

**Comment by dualcoding** [comment]
@Kkthnx @goldpaw 
This is now a separate addon over at https://github.com/dualcoding/wow-profiler/
*Very* alpha, right now it pretty much taints everything.

**Comment by dualcoding** [comment]
@Kkthnx @goldpaw 
Last notice in this thread! There should be no more taint, the profiler now has basic columns, and the entries can be sorted by memory, cpu, number of calls and name.

As such, the basic functionality is there. Future improvements will focus on making the UI more pleasant to use then putting your hand into a meat grinder and trying to provide more useful information to developers. No time plan for any of this. Feel free to open issues and pull requests if you happen to find it useful.

Cheers!

**Comment by goldpaw** [comment]
Kickass work! That's a compiiment ;)

**Comment by Kkthnx** [comment]
Godlikeeee!

**Pull request closed without merging**
